---
- name: Setup Docker-Server
  hosts: localhost
  remote_user: root

  tasks:

  - name: Hello Server
    debug:
      msg: "Hello DEVK!!" 
      
  - name: Create file
    file:
    state: touch
    path: /temp
