---
- name: Setup Docker-Server
  hosts: localhost
  remote_user: root

  tasks:

  - name: Hello Server
    debug:
      msg: "Hello World!" 
        
  - name: Erstelle eine Datei
    file:
      path: /tmp/NEUE_DATEI
      state: touch

  - name: Hello Variable
    debug:
      msg: "{{ Test | upper }}" 

  - name: Hello Loop
    debug:
      msg: {{ item }}
      
      loop: 
        -test1
        -test2
        -test3
